version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.7
    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            pip install nose
            pip install pytest
            pip install coverage

      - run:
          name: Run Unit Tests
          command: |
            coverage run --source=app -m nose tests/unit
            coverage report -m

      - run:
          name: Run Integration Tests
          command: |
            coverage run --source=app -m nose tests/integration
            coverage report -m

      - run:
          name: Run Acceptance Tests
          command: |
            pytest tests/acceptance

workflows:
  build_and_test:
    jobs:
      - build